service: play-port-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  environment:
    WATCHMODE_API_KEY: ${env:WATCHMODE_API_KEY}

functions:
  searchByName:
    handler: functions/handler.searchByName
    events:
      - httpApi:
          path: /search
          method: get
  autocomplete:
    handler: functions/handler.autocomplete
    events:
      - httpApi:
          path: /autocomplete
          method: get
  getStreamingSources:
    handler: functions/handler.getStreamingSources
    events:
      - httpApi:
          path: /title/{id}/sources
          method: get

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: [ 'aws-sdk' ]
    target: 'node20'
    define: { 'require.resolve': undefined }
    platform: 'node'
    tsconfig: 'functions/tsconfig.json'


