service: play-port-api

provider:
  name: aws
  runtime: nodejs24.x
  region: eu-central-1
  environment:
    WATCHMODE_API_KEY: ${env:WATCHMODE_API_KEY}
    TMDB_READ_ACCESS_TOKEN: ${env:TMDB_READ_ACCESS_TOKEN}

functions:
  search:
    handler: functions/handler.search
    events:
      - httpApi:
          path: /search
          method: get
  getMovieProviders:
    handler: functions/handler.getMovieProviders
    events:
      - httpApi:
          path: /movie/{movieId}/providers
          method: get
  getTvProviders:
    handler: functions/handler.getTvProviders
    events:
      - httpApi:
          path: /tv/{seriesId}/providers
          method: get
  getRegions:
    handler: functions/handler.getRegions
    events:
      - httpApi:
          path: /regions
          method: get

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: [ 'aws-sdk' ]
    target: 'node20'
    define: { 'require.resolve': undefined }
    platform: 'node'
    tsconfig: 'functions/tsconfig.json'


