"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _title_item from './title-item.bones.json'
import _source_item from './source-item.bones.json'

configureBoneyard({"color":"rgba(169, 148, 222, 0.10)","darkColor":"rgba(169, 148, 222, 0.10)","animate":"shimmer","shimmerColor":"rgba(201, 190, 236, 0.18)","darkShimmerColor":"rgba(201, 190, 236, 0.18)","speed":"1.6s","shimmerAngle":90,"transition":200})

registerBones({
  "title-item": _title_item,
  "source-item": _source_item,
})
